language: cpp
compiler:
  - gcc
  - clang
dist: bionic
before_install: sudo apt-get install -y cmake libgd-dev libsqlite3-dev libleveldb-dev
script: ./util/travis/script.sh
notifications:
  email: false
matrix:
  fast_finish: true
