language: cpp
compiler:
  - gcc
  - clang
sudo: false
dist: trusty
addons:
  apt:
    sources:
      - llvm-toolchain-trusty-5.0
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - libgd2-dev
      - libsqlite3-dev
      - libleveldb-dev
      - g++-7
      - clang-5.0
script: ./util/travis/script.sh
notifications:
  email: false
matrix:
  fast_finish: true
